# Site settings
name: Christian Alexander
description: "The Worlds of alexforsale"
url: ""


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  alexforsale
#codepen_username: your_codepen_username_goes_here
facebook_username: alexforsale
#vk_username: your_vk_username_goes_here
twitter_username: alexforsale
google_plus_username: ChristianAlexander
#linkedin_username: your_linked_in_username_goes_here
#vine_username:  your_vine_username_goes_here
instagram_username:  alexforsale
flickr_username: alexforsale
steam_username: alexforsale
#soundcloud_username:  your_soundcloud_username_goes_here
stack_of_username: 9088776/alexforsale
reddit_username: elasrofxela
#medium_username:  your_medium_username_goes_here
#tumblr_username: your_tumblr_username_goes_here
#weibo_username: your_weibo_username_goes_here
lastfm_username: alexforsale
blog_url: "blog/"
email: alexforsale@yahoo.com
public_key_url: https://pastebin.com/Fx3wFLdH


avatar: yes
#avatar_img_path: "imgs/alexforsale.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars2.githubusercontent.com/u/4062073"


front_img: yes
front_img_path: "imgs/dark-grey-texture.jpeg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/alexforsale_small.jpg"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
